openapi: 3.0.0
info:
  title: API-gateway
  description: OpenAPI definition
  version: 1.0.0
servers:
  - url: "http://api.example.com"
tags:
  - name: user-access
    description: Operations related to User Access functionality
  - name: registrations
    description: Operations related to Registration functionality
paths:

  /api/v1/registrations:
    post:
      $ref: './resources/registrations/new_registration.yaml'

  /api/v1/registrations/{registration_uuid}/confirm:
    post:
      $ref: './resources/registrations/confirm_registration.yaml'

  /api/v1/user-access/login:
    post:
      $ref: './resources/user-access/login.yaml'
